version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    volumes:
      - todo-db:/usr/src/app/data
    environment:
      - PORT=5000

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://localhost:5001/api/todos
    depends_on:
      - backend

volumes:
  todo-db:
